"""upgrage

Revision ID: 05ff71110258
Revises: a789f99657a4
Create Date: 2019-05-07 22:55:16.736216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ff71110258'
down_revision = 'a789f99657a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(length=32), nullable=True))
    op.add_column('book', sa.Column('type', sa.String(length=32), nullable=True))
    op.add_column('book', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_book_author'), 'book', ['author'], unique=False)
    op.create_index(op.f('ix_book_type'), 'book', ['type'], unique=False)
    op.create_index(op.f('ix_book_year'), 'book', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_year'), table_name='book')
    op.drop_index(op.f('ix_book_type'), table_name='book')
    op.drop_index(op.f('ix_book_author'), table_name='book')
    op.drop_column('book', 'year')
    op.drop_column('book', 'type')
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
